version: '3.8'

services:
  app:
    image: pedruhf/dinheirow-test:1.0.2-22
    ports:
      - 3000:3000
  
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
